#!/usr/bin/env python3
"""Bootstrap a dedicated RunLedger org for the LocalAI Agent Stack demo.

The script is intentionally idempotent for org/workspace creation. It stores raw
workspace API keys in an ignored local state file because RunLedger only shows the
full key once at creation time.
"""

from __future__ import annotations

import argparse
import json
import os
import sys
from datetime import UTC, datetime
from pathlib import Path
from typing import Any
from urllib import error, request


DEFAULT_WORKSPACES = [
    "LiteLLM Gateway",
    "Open WebUI",
    "OpenHands",
    "LangGraph",
    "Hermes Agent",
    "Claude Desktop",
    "OpenAI Codex",
    "Python Console",
    "Backup Restore Lab",
]


def _json_request(
    method: str,
    url: str,
    body: dict[str, Any] | None = None,
    *,
    api_key: str | None = None,
    expected: tuple[int, ...] = (200, 201, 202, 204),
) -> Any:
    data = json.dumps(body or {}).encode("utf-8") if body is not None else None
    headers = {"Accept": "application/json"}
    if body is not None:
        headers["Content-Type"] = "application/json"
    if api_key:
        headers["Authorization"] = f"Bearer {api_key}"
    req = request.Request(url, data=data, headers=headers, method=method)
    try:
        with request.urlopen(req, timeout=30) as resp:
            raw = resp.read()
            if resp.status not in expected:
                raise RuntimeError(f"{method} {url} -> {resp.status}: {raw[:200]!r}")
            return json.loads(raw.decode("utf-8")) if raw else {}
    except error.HTTPError as exc:
        text = exc.read().decode("utf-8", errors="replace")
        if exc.code not in expected:
            raise RuntimeError(f"{method} {url} -> {exc.code}: {text[:300]}") from exc
        return json.loads(text) if text else {}


def _load_state(path: Path) -> dict[str, Any]:
    if not path.exists():
        return {"workspaces": {}}
    return json.loads(path.read_text(encoding="utf-8"))


def _save_state(path: Path, state: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(state, indent=2, sort_keys=True) + "\n", encoding="utf-8")


def _env_name(name: str) -> str:
    return (
        "RUNLEDGER_KEY_"
        + name.upper()
        .replace("&", "AND")
        .replace("-", "_")
        .replace(" ", "_")
        .replace("/", "_")
    )


def _write_localai_files(stack: Path, base_url: str, org_admin_email: str, org_admin_password: str, state: dict[str, Any]) -> None:
    config_dir = stack / "config" / "runledger"
    workspace_dir = stack / "workspaces"
    config_dir.mkdir(parents=True, exist_ok=True)
    workspace_dir.mkdir(parents=True, exist_ok=True)

    env_lines = [
        "# Generated by runledger-community/scripts/localai/bootstrap_runledger_org.py",
        "# Keep this file private. It contains workspace API keys.",
        f"RUNLEDGER_BASE_URL={base_url}",
        f"RUNLEDGER_GATEWAY_BASE_URL={base_url}/gateway",
        f"RUNLEDGER_MCP_URL={base_url}/mcp",
        "RUNLEDGER_OTLP_HTTP=http://localhost:4318/v1/traces",
        f"RUNLEDGER_ORG_ADMIN_EMAIL={org_admin_email}",
        f"RUNLEDGER_ORG_ADMIN_PASSWORD={org_admin_password}",
        "",
    ]
    for name, ws in sorted(state.get("workspaces", {}).items()):
        key = ws.get("api_key", "")
        if key:
            env_lines.append(f"{_env_name(name)}={key}")
    (config_dir / "runledger.env").write_text("\n".join(env_lines) + "\n", encoding="utf-8")

    public_lines = [
        "# RunLedger LocalAI Agent Stack Integration",
        "",
        "This workspace is wired to the dedicated RunLedger org `LocalAI Agent Stack`.",
        "",
        "Use these endpoints from host tools:",
        "",
        f"- API: `{base_url}`",
        f"- Gateway: `{base_url}/gateway`",
        f"- MCP HTTP: `{base_url}/mcp`",
        "- OTLP HTTP: `http://localhost:4318/v1/traces`",
        "",
        "Use these endpoints from Docker containers:",
        "",
        "- API: `http://host.docker.internal:8201`",
        "- Gateway: `http://host.docker.internal:8201/gateway`",
        "- OTLP HTTP: `http://host.docker.internal:4318/v1/traces`",
        "",
        "Workspace mapping:",
        "",
        "| Workspace | Env var |",
        "|---|---|",
    ]
    for name in sorted(state.get("workspaces", {})):
        public_lines.append(f"| {name} | `{_env_name(name)}` |")
    public_lines += [
        "",
        "The private values live in `config/runledger/runledger.env` in this LocalAIStack repo.",
        "Do not commit that file.",
        "",
        "Why Claude/Codex are not always inline:",
        "",
        "Claude Desktop and Codex can call MCP tools and local scripts, but their native hosted model calls are not generally routed through a user-controlled OpenAI-compatible base URL. For those tools, RunLedger uses MCP/SDK/hook telemetry out of band. To demonstrate true inline control, route an OpenAI-compatible client, LiteLLM, Open WebUI, OpenHands, or a Python console through RunLedger Gateway.",
    ]
    (workspace_dir / "RUNLEDGER.md").write_text("\n".join(public_lines) + "\n", encoding="utf-8")

    agent_lines = [
        "# RunLedger Agent Instructions",
        "",
        "Every agent spawned from this LocalAI stack should attach RunLedger metadata to its work.",
        "",
        "Required environment variables:",
        "",
        "```text",
        "RUNLEDGER_BASE_URL=http://localhost:8201",
        "RUNLEDGER_GATEWAY_BASE_URL=http://localhost:8201/gateway",
        "RUNLEDGER_OTLP_HTTP=http://localhost:4318/v1/traces",
        "RUNLEDGER_API_KEY=<workspace key from config/runledger/runledger.env>",
        "```",
        "",
        "When the agent controls an OpenAI-compatible client, use inline mode:",
        "",
        "```python",
        "from openai import OpenAI",
        "",
        "client = OpenAI(",
        "    base_url='http://localhost:8201/gateway',",
        "    api_key=os.environ['RUNLEDGER_API_KEY'],",
        ")",
        "```",
        "",
        "When inline mode is not possible, use out-of-band mode:",
        "",
        "- Emit SDK events with run id, agent name, feature tag, user/session, model, cost, latency, and outcome.",
        "- Emit OTLP spans to `http://localhost:4318/v1/traces` with the RunLedger API key.",
        "- Use RunLedger MCP tools for budget checks, policy/tool filtering, analytics lookup, and optimization recommendations.",
        "",
        "Recommended metadata keys:",
        "",
        "```json",
        "{",
        '  "agent_client": "open-webui|openhands|langgraph|hermes|claude-desktop|codex|python-console",',
        '  "team": "Engineering|Support|Finance|Research",',
        '  "application": "LocalAI Agent Stack",',
        '  "workspace": "one of the RunLedger workspaces",',
        '  "control_path": "gateway|sdk|mcp|otlp|wrapper"',
        "}",
        "```",
        "",
        "Claude Desktop and Codex native model calls are usually not inline-routable. Use MCP or wrapper telemetry for those, and route any spawned OpenAI-compatible subprocess through RunLedger Gateway when possible.",
    ]
    (workspace_dir / "runledger-agent-instructions.md").write_text("\n".join(agent_lines) + "\n", encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description="Create the LocalAI Agent Stack org/workspaces in RunLedger.")
    parser.add_argument("--base-url", default=os.getenv("RUNLEDGER_BASE_URL", "http://localhost:8201"))
    parser.add_argument("--platform-email", default=os.getenv("RUNLEDGER_PLATFORM_EMAIL", "admin@homelab.com"))
    parser.add_argument("--platform-password", default=os.getenv("RUNLEDGER_PLATFORM_PASSWORD", "Dell1234"))
    parser.add_argument("--org-name", default="LocalAI Agent Stack")
    parser.add_argument("--org-admin-email", default="admin@localai-agent-stack.example.com")
    parser.add_argument("--org-admin-password", default="LocalAIStack123!")
    parser.add_argument("--org-admin-name", default="LocalAI Stack Admin")
    parser.add_argument("--state-file", default="scripts/.localai-runledger.json")
    parser.add_argument("--localai-stack", default=r"C:\Users\Abi\Desktop\LocalAIAgentStack")
    parser.add_argument("--rotate-keys", action="store_true", help="mint fresh keys even if local state already has one")
    args = parser.parse_args()

    base_url = args.base_url.rstrip("/")
    state_path = Path(args.state_file)
    state = _load_state(state_path)
    state.update(
        {
            "base_url": base_url,
            "org_name": args.org_name,
            "org_admin_email": args.org_admin_email,
            "org_admin_password": args.org_admin_password,
            "updated_at": datetime.now(UTC).isoformat(),
        }
    )
    state.setdefault("workspaces", {})

    platform_login = _json_request(
        "POST",
        f"{base_url}/auth/login",
        {"email": args.platform_email, "password": args.platform_password},
    )
    platform_key = platform_login["api_key"]
    tenants = _json_request("GET", f"{base_url}/org/tenants", api_key=platform_key)
    tenant = next((item for item in tenants if item.get("name") == args.org_name), None)
    if tenant is None:
        print(f"Creating org: {args.org_name}")
        try:
            tenant = _json_request(
                "POST",
                f"{base_url}/org/tenants",
                {
                    "name": args.org_name,
                    "admin_email": args.org_admin_email,
                    "admin_password": args.org_admin_password,
                    "admin_full_name": args.org_admin_name,
                    "skip_verification": True,
                },
                api_key=platform_key,
                expected=(201,),
            )
        except RuntimeError as exc:
            print(f"Could not create org: {exc}", file=sys.stderr)
            raise
    else:
        print(f"Using existing org: {args.org_name}")
    state["tenant_id"] = tenant.get("id")

    org_login = _json_request(
        "POST",
        f"{base_url}/auth/login",
        {"email": args.org_admin_email, "password": args.org_admin_password},
    )
    org_key = org_login["api_key"]
    existing_workspaces = _json_request("GET", f"{base_url}/org/workspaces", api_key=org_key)
    by_name = {item["name"]: item for item in existing_workspaces}

    if args.org_name + " Workspace" in by_name and DEFAULT_WORKSPACES[0] not in by_name:
        default_ws = by_name.pop(args.org_name + " Workspace")
        renamed = _json_request(
            "PUT",
            f"{base_url}/org/workspaces/{default_ws['id']}",
            {"name": DEFAULT_WORKSPACES[0]},
            api_key=org_key,
        )
        by_name[renamed["name"]] = renamed

    for name in DEFAULT_WORKSPACES:
        if name not in by_name:
            print(f"Creating workspace: {name}")
            created = _json_request("POST", f"{base_url}/org/workspaces", {"name": name}, api_key=org_key, expected=(201,))
            by_name[name] = created

    for name in DEFAULT_WORKSPACES:
        ws = by_name[name]
        entry = state["workspaces"].setdefault(name, {})
        entry.update({"workspace_id": ws["id"], "workspace_name": name})
        if args.rotate_keys or not entry.get("api_key"):
            print(f"Minting API key: {name}")
            key_resp = _json_request(
                "POST",
                f"{base_url}/settings/api-keys",
                {"name": "localai-stack", "workspace_id": ws["id"]},
                api_key=org_key,
                expected=(201,),
            )
            entry["api_key"] = key_resp["key"]
            entry["key_prefix"] = key_resp.get("key_prefix")

    _save_state(state_path, state)
    _write_localai_files(Path(args.localai_stack), base_url, args.org_admin_email, args.org_admin_password, state)

    print(f"\nWrote local state: {state_path}")
    print(f"Wrote LocalAIStack env: {Path(args.localai_stack) / 'config' / 'runledger' / 'runledger.env'}")
    print(f"Org admin: {args.org_admin_email} / {args.org_admin_password}")
    print("Workspaces:")
    for name in DEFAULT_WORKSPACES:
        entry = state["workspaces"][name]
        print(f"  - {name}: {entry['workspace_id']} ({entry.get('key_prefix', 'key saved')})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
