apiVersion: v1
kind: Service
metadata:
  name: {{ include "runledger.fullname" . }}-api
  labels:
    {{- include "runledger.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  type: {{ .Values.service.api.type }}
  ports:
    - port: {{ .Values.service.api.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "runledger.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "runledger.fullname" . }}-web
  labels:
    {{- include "runledger.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  type: {{ .Values.service.web.type }}
  ports:
    - port: {{ .Values.service.web.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "runledger.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: web
