apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "runledger.fullname" . }}-worker
  labels:
    {{- include "runledger.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker
spec:
  {{- if not .Values.autoscaling.worker.enabled }}
  replicas: {{ .Values.worker.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "runledger.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: worker
  template:
    metadata:
      annotations:
        checksum/values: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "runledger.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: worker
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "runledger.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: worker
          securityContext:
            {{- toYaml .Values.containerSecurityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - celery
            - -A
            - runledger_api.core.celery_app
            - worker
            - --loglevel=info
            - --concurrency=4
            - -Q
            - celery,priority,low
          env:
            {{- include "runledger.commonEnv" . | nindent 12 }}
          resources:
            {{- toYaml .Values.worker.resources | nindent 12 }}
          {{- if .Values.pricingConfig.enabled }}
          volumeMounts:
            - name: pricing-config
              mountPath: /app/pricing.yml
              subPath: pricing.yml
              readOnly: true
          {{- end }}
      {{- if .Values.pricingConfig.enabled }}
      volumes:
        - name: pricing-config
          configMap:
            name: {{ .Values.pricingConfig.configMapName }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
